---
title: "ROI_data"
author: "Tristan Caro"
date: "7/3/2021"
output: html_document
---

# Collecting ROI Data

ROI data has been collected into a folder `June_2021/roi_data`

```{r}
# Load Libraries
library(tidyverse)
library(readxl)
library(ggsci)
library(ggdist)
```

```{r, echo=FALSE, message=FALSE}
temp_list = list.files(path = "June_2021/roi_data", pattern="*.tsv")
#roi_data = lapply(paste0("June_2021/roi_data/", temp), read_tsv)

# Create an empty tibble with pre-defined colnames
# I wish I knew a better way to create an empty tibble but this will have to do
tbl_colnames <- c("N_source", "light", "inc_time_hr", "ROI", "12C", "13C", "14N_12C", "15N_12C", "31P", "32S", "34S", "SE", "Ratio_15N_12Cx14N_12C" )
roi_tbl <- tibble(
)
roi_tbl <- roi_tbl[-1,] # Remove the garbage row of the tibble

# Read in each .tsv, append each to the roi_tbl we just generated
for (tsv in temp_list) {
  tmp_df <- read_tsv(paste0("June_2021/roi_data/", tsv))
  tmp_df <- tmp_df %>% mutate(filename = tsv)
  roi_tbl <- bind_rows(roi_tbl, tmp_df)
}
```

```{r}
# Parse filenames to generate conditions
roi_tbl <- roi_tbl %>% mutate(
  N_source = case_when(
    str_detect(filename, regex('NH4', ignore_case = TRUE)) ~ "NH4",
    str_detect(filename, regex('no3', ignore_case = TRUE)) ~ "no3",
    str_detect(filename, regex('TMA', ignore_case = TRUE)) ~ "TMA",
    str_detect(filename, regex('gly', ignore_case = TRUE)) ~ "gly",
    str_detect(filename, regex('CN', ignore_case = TRUE)) ~ "CN"),
  light = case_when(
    str_detect(filename, "light") ~ "light",
    str_detect(filename, "dark") ~ "dark"),
  incubation_time_hr = 96,
  cell_type = case_when(
    Group == "red" ~ "Picocystis",
    Group == "green" ~ "Picocystis triplet",
    Group == "blue" ~ "Other"
  )
)
```

```{r}
# Write master .tsv file for posterity or other analyses
write_tsv(roi_tbl, "roi_tbl.tsv")
```


# Plot!
```{r}
p_roi_tbl_1 <- roi_tbl %>% ggplot(aes(x = N_source, y=Ratio_15N_12Cx14N_12C, color = cell_type)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position=position_jitterdodge(jitter.width = 0.1), size = 0.2) +
  scale_color_aaas() +
  facet_wrap(vars(light)) +
  geom_hline(yintercept = .00364, color = "red") +
  theme_classic()
ggsave(plot = p_roi_tbl_1, filename = "p_roi_tbl1.png")
p_roi_tbl_1

p_roi_tbl_1_dark <- roi_tbl %>% 
  filter(light == "dark") %>% 
  ggplot(aes(x = N_source, y = Ratio_15N_12Cx14N_12C, color = cell_type)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position=position_jitterdodge(jitter.width = 0.1), size = 0.2) +
  scale_color_aaas() +
  geom_hline(yintercept = .00364, color = "red") +
  theme_classic()
p_roi_tbl_1_dark
```

```{r}
# Raincloud plotting
roi_tbl %>% filter(N_source == "NH4") %>% 
  ggplot(aes(x = Ratio_15N_12Cx14N_12C, fill = cell_type)) + 
  stat_slab(alpha = 0.3, height = 0.5) +
  stat_pointinterval(position = position_dodge(width = .4, preserve = "single")) +
  scale_fill_aaas() +
  theme_classic()
```

